name: GitHub Pages deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "22.x"

      - name: Install dependencies
        run: npm ci

      - name: Extract repository name 
        run: echo "BASE_PATH=/$(echo $GITHUB_REPOSITORY | cut -d '/' -f 2)" >> $GITHUB_ENV

      - name: Build
        run: npm run build && touch ./out/.nojekyll

      - name: Deploy
        uses: joshdice/github-pages-deploy-action@v4
        with:
          branch: gh-pages # The branch to deploy to
          folder: out # The folder containing build output